import Head from "next/head";
import Link from "next/link";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>Main page</h1>
        <Link href='/welcome' >Login</Link>

      </section>
    </div>
  );
}
Home.exclude = true;
