import Head from "next/head"
import Link from "next/link"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Q U R A N L Y</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen gap-2 flex flex-col justify-center items-center bg-gradient-to-b from-red-700 to-black">
        <h1>Main page</h1>
        <Link href="/app/" className="px-8 py-4 bg-black rounded-lg">
          App
        </Link>
      </main>
    </div>
  )
}
Home.exclude = true
